name: flutter_application_1
description: A new Flutter project.

# Versão do SDK
environment:
  sdk: ">=2.19.0 <3.0.0"


# Dependências para desenvolvimento
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter
flutter:
  uses-material-design: true

 